# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 418e533ee1241dd02f7c7e9fb3f61cbdc6336cf2a39ffff1b89a4b14c8a21b02f5aca6ece31c4e44716926fc8a4caf29ae2f21188fd9ce4a8d9e184fdb6418c2

test:
  secret_key_base: faf7699ae41b6e020fea6c8700d9c7394d9fe157cd7e133f3704c6dc0da727195d247ea3716af1270386cc80530462a794da386e96e773ce4c9af8f4cb2af335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
